#58 replace dto with record-classes
philippe-fredrik/corkdork pull request #61
Opened 2022-03-27 13:19 UTC by ErikssonF

2022-03-29 08:08 UTC, Philippevial requested changes

2022-03-29 08:08 UTC, Philippevial commented on src/main/java/se/iths/corkdork/controller/CountryController.java
> +//        if(country.getName().isEmpty())
Why is this code commented out? In the other controllers as well

2022-03-29 08:09 UTC, Philippevial commented on src/main/java/se/iths/corkdork/entity/GrapeEntity.java
> +    @NotNull
we should use @Column(nullable=false) instead of @notnull

2022-04-04 13:28 UTC, ErikssonF commented
After trying it out, it seems that some features won't work out properly if we migrate to record classes, so I'll close this issue.

2022-04-04 13:28 UTC, closed without merging